project:
  type: website
  preview:
    browser: true
  render:
    - quarto_site/index.qmd
    - quarto_site/research_questions.md
    - quarto_site/summary.qmd
    - quarto_site/analysis.ipynb

website:
  title: "The STRESS Guidelines: A first update."
  # Favicon image for site
  favicon: "quarto_site/stars_logo_blue.png"
  # Adds edit and issue buttons to footer
  repo-url: https://github.com/pythonhealthdatascience/stress_update
  repo-actions: [edit, issue]
  navbar:
    logo: "quarto_site/stars_logo_blue.png"
    left:
      - href: quarto_site/index.qmd
      - text: Study summary
        menu:
           - quarto_site/research_questions.md
           - quarto_site/summary.qmd
      - text: Analysis notebook
        href: quarto_site/analysis.ipynb

format:
  html:
    theme: cosmo
    toc: true